import { useEffect, useState } from 'react';
import { approveOwnershipReview, getPendingOwnershipReviews, rejectOwnershipReview } from '../../api/securityOwnershipVerifications';
import { Alert, EmptyState, PageLoading } from '../../components/Ui';

export default function SecurityOwnershipReviewsPage() {
  const [reviews, setReviews] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [notes, setNotes] = useState({}); const [working, setWorking] = useState('');
  const load = () => getPendingOwnershipReviews().then(setReviews).catch(e => setError(e.message)).finally(() => setLoading(false)); useEffect(load, []);
  const decide = async (review, approve) => { setWorking(review.claimId); setError(''); try { await (approve ? approveOwnershipReview : rejectOwnershipReview)(review.verificationId, notes[review.claimId] || ''); setReviews(x => x.filter(item => item.claimId !== review.claimId)); } catch (e) { setError(e.message); } finally { setWorking(''); } };
  if (loading) return <PageLoading label="Loading ownership verification reviews…" />;
  return <div className="page-container-wide"><div className="page-header"><div><span className="eyebrow">Security Desk</span><h1>Ownership Verification Reviews</h1><p>Review claimant answers against finder-only identifying details. Security makes the decision.</p></div></div><Alert type="error">{error}</Alert>{reviews.length === 0 ? <EmptyState title="No ownership reviews waiting" message="Submitted verifications will appear here." /> : <div style={{ display: 'grid', gap: 18 }}>{reviews.map(review => <article className="card card-pad-lg" key={review.claimId}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, flexWrap: 'wrap' }}><div><h2 style={{ fontSize: '1.15rem' }}>{review.claimNumber} · {review.foundItemTitle || 'Found item'}</h2><p className="text-secondary">AI Match Confidence: <strong>{Math.round(review.matchConfidenceScore)}%</strong> · Claimant: {review.studentName || review.studentEmail} · Finder: {review.finderName || review.finderEmail}</p></div><span className="badge badge-warning">Pending Security Review</span></div><section style={{ marginTop: 18, padding: 16, background: 'var(--warning-bg)', borderRadius: 'var(--radius-md)' }}><strong>Private Finder Details</strong><p style={{ whiteSpace: 'pre-wrap', marginTop: 8 }}>{review.privateVerificationDetails}</p></section><div style={{ display: 'grid', gap: 12, marginTop: 18 }}>{review.questions.map((q, index) => <section key={q.id} style={{ padding: 14, border: '1px solid var(--border)', borderRadius: 'var(--radius-md)' }}><strong>Question {index + 1}</strong><p>{q.question}</p><p className="text-secondary"><strong>Claimant answer:</strong> {q.studentAnswer || 'No answer'}</p></section>)}</div><div className="form-field" style={{ marginTop: 18 }}><label htmlFor={`note-${review.claimId}`}>Security review note (optional)</label><textarea id={`note-${review.claimId}`} rows={2} value={notes[review.claimId] || ''} onChange={e => setNotes(x => ({ ...x, [review.claimId]: e.target.value }))} /></div><div style={{ display: 'flex', gap: 10, marginTop: 12 }}><button className="btn btn-primary" disabled={working === review.claimId} onClick={() => decide(review, true)}>Approve Ownership</button><button className="btn btn-danger" disabled={working === review.claimId} onClick={() => decide(review, false)}>Reject Ownership</button></div></article>)}</div>}</div>;
}
