using System.Text.Json;
using CampusFindAI.Api.DTOs; using CampusFindAI.Api.Models; using CampusFindAI.Api.Repositories; using CampusFindAI.Api.Services; using Microsoft.AspNetCore.DataProtection; using Microsoft.Extensions.Options;
namespace CampusFindAI.Api.Tests;
public sealed class OwnershipVerificationServiceTests
{
 [Fact] public async Task Below60_CannotStart(){var f=New(59);await Assert.ThrowsAsync<InvalidOperationException>(()=>f.S.StartForMatchAsync(f.M.Id,"owner"));}
 [Fact] public async Task At60_CanStartAndQuestionsDoNotRevealPrivateDetails(){var f=New(60);var r=await f.S.StartForMatchAsync(f.M.Id,"owner");Assert.Equal("InProgress",r.Status);Assert.DoesNotContain("silver zipper",JsonSerializer.Serialize(r),StringComparison.OrdinalIgnoreCase);}
 [Fact] public async Task Submission_IsPendingSecurityReview_AndNeverCallsEvaluator(){var f=New();await f.S.StartForMatchAsync(f.M.Id,"owner");var r=await f.S.SubmitForMatchAsync(f.M.Id,"owner",Answers());Assert.Equal("PendingSecurityReview",r.Status);Assert.False(r.CanAccessHandoverChat);}
 [Fact] public async Task UnrelatedStudent_CannotAccess(){var f=New();await Assert.ThrowsAsync<UnauthorizedAccessException>(()=>f.S.StartForMatchAsync(f.M.Id,"other"));}
 [Fact] public async Task PendingReview_IsVisibleToSecurityWithPrivateDetails(){var f=New();await Submit(f);var r=Assert.Single(await f.S.GetPendingSecurityReviewsAsync());Assert.Equal("silver zipper",r.PrivateVerificationDetails);Assert.Equal("answer one",r.Questions[0].StudentAnswer);}
 [Fact] public async Task Approval_SetsApprovedReviewerTimeAndUnlocksChat(){var f=New();await Submit(f);var v=Assert.Single(await f.S.GetPendingSecurityReviewsAsync());var r=await f.S.DecideSecurityReviewAsync(v.VerificationId,"officer",true,"confirmed");Assert.Equal("Approved",r.Status);Assert.Equal("officer",r.SecurityReviewedByUserId);Assert.NotNull(r.SecurityReviewedAt);Assert.True(await f.S.CanAccessHandoverChatAsync(f.M.Id,"owner"));}
 [Fact] public async Task Rejection_KeepsChatLockedAndAllowsRetry(){var f=New();await Submit(f);var v=Assert.Single(await f.S.GetPendingSecurityReviewsAsync());await f.S.DecideSecurityReviewAsync(v.VerificationId,"officer",false,"not enough");var status=await f.S.GetStatusAsync(f.M.Id,"owner");Assert.Equal("Rejected",status.Status);Assert.True(status.CanStart);Assert.False(status.CanAccessHandoverChat);}
 [Fact] public async Task FinalRejection_ExhaustsAttempts(){var f=New();await Submit(f);var a=Assert.Single(await f.S.GetPendingSecurityReviewsAsync());await f.S.DecideSecurityReviewAsync(a.VerificationId,"officer",false,null);await f.S.StartForMatchAsync(f.M.Id,"owner");await f.S.SubmitForMatchAsync(f.M.Id,"owner",Answers());var b=Assert.Single(await f.S.GetPendingSecurityReviewsAsync());var r=await f.S.DecideSecurityReviewAsync(b.VerificationId,"officer",false,null);Assert.Equal("AttemptsExhausted",r.Status);}
 [Fact] public async Task Approval_NotifiesClaimantAndFinderOnce(){var f=New();await Submit(f);var v=Assert.Single(await f.S.GetPendingSecurityReviewsAsync());await f.S.DecideSecurityReviewAsync(v.VerificationId,"officer",true,null);Assert.Contains(f.N.Messages,x=>x.StartsWith("owner:"));Assert.Contains(f.N.Messages,x=>x.StartsWith("finder:"));}
 [Fact] public async Task PublicDtos_DoNotContainPrivateDetails(){Assert.Null(typeof(FoundItemDto).GetProperty("PrivateVerificationDetails"));Assert.Null(typeof(MatchDto).GetProperty("PrivateVerificationDetails"));await Task.CompletedTask;}
 [Fact] public async Task EmptyAnswers_AreRejected(){var f=New();await f.S.StartForMatchAsync(f.M.Id,"owner");await Assert.ThrowsAsync<InvalidOperationException>(()=>f.S.SubmitForMatchAsync(f.M.Id,"owner",new(){Answers=["","two","three"]}));}
 [Fact] public async Task Audit_ExcludesPrivateDetailsAndAnswers(){var f=New();await Submit(f);Assert.All(f.A.D,x=>{Assert.DoesNotContain("silver zipper",x);Assert.DoesNotContain("answer one",x);});}
 static async Task Submit(F f){await f.S.StartForMatchAsync(f.M.Id,"owner");await f.S.SubmitForMatchAsync(f.M.Id,"owner",Answers());} static SubmitVerificationRequestDto Answers()=>new(){Answers=["answer one","answer two","answer three"]};
 static F New(decimal confidence=80){var m=new Match{Id=Guid.NewGuid(),ConfidenceScore=confidence,LostItem=new(){Id=Guid.NewGuid(),UserId="owner",Status="Open"},FoundItem=new(){Id=Guid.NewGuid(),UserId="finder",Status="Available",Title="Wallet",PrivateVerificationDetails="silver zipper"}};m.LostItemId=m.LostItem.Id;m.FoundItemId=m.FoundItem.Id;var c=new C();var v=new V();var a=new A();var n=new N();var s=new OwnershipVerificationService(c,new Fnd(m.FoundItem),new M(m),v,new U(),a,n,new EphemeralDataProtectionProvider(),new G(),Options.Create(new OwnershipVerificationOptions{MatchEligibilityThreshold=.60m,QuestionCount=3,MaxAttempts=2}));return new(s,m,v,a,n);} record F(OwnershipVerificationService S,Match M,V V,A A,N N);
 sealed class G:IOwnershipQuestionGenerator{public Task<OwnershipQuestionGenerationResult> GenerateAsync(string d,int n,CancellationToken c=default)=>Task.FromResult(new OwnershipQuestionGenerationResult(Enumerable.Range(1,n).Select(i=>new OwnershipQuestion($"Question {i}",$"fact {i}")).ToList(),false));}
 sealed class M(Match m):IMatchRepository{public Task<Match?> GetByIdAsync(Guid i,CancellationToken c=default)=>Task.FromResult<Match?>(i==m.Id?m:null);public Task<IReadOnlyList<Match>> GetByFoundItemIdAsync(Guid i,CancellationToken c=default)=>Task.FromResult((IReadOnlyList<Match>)[m]);public Task<IReadOnlyList<Match>> GetAllAsync(CancellationToken c=default)=>Task.FromResult((IReadOnlyList<Match>)[m]);public Task<IReadOnlyList<Match>> GetByLostItemUserIdAsync(string i,CancellationToken c=default)=>Task.FromResult((IReadOnlyList<Match>)[m]);public Task<bool> ExistsAsync(Guid a,Guid b,CancellationToken c=default)=>Task.FromResult(false);public Task AddAsync(Match x,CancellationToken c=default)=>Task.CompletedTask;public Task SaveChangesAsync(CancellationToken c=default)=>Task.CompletedTask;}
 sealed class Fnd(FoundItem x):IFoundItemRepository{public Task<FoundItem?> GetByIdAsync(Guid i,CancellationToken c=default)=>Task.FromResult<FoundItem?>(x);public Task AddAsync(FoundItem y,CancellationToken c=default)=>Task.CompletedTask;public Task<IReadOnlyList<FoundItem>> GetAllAsync(CancellationToken c=default)=>Task.FromResult((IReadOnlyList<FoundItem>)[x]);public Task<IReadOnlyList<FoundItem>> GetByUserIdAsync(string i,CancellationToken c=default)=>Task.FromResult((IReadOnlyList<FoundItem>)[x]);public Task UpdateStatusAsync(Guid i,string s,CancellationToken c=default)=>Task.CompletedTask;public Task SaveChangesAsync(CancellationToken c=default)=>Task.CompletedTask;}
 sealed class C:IClaimRepository{public List<Claim>D=[];public Task AddAsync(Claim x,CancellationToken c=default){D.Add(x);return Task.CompletedTask;}public Task<Claim?> GetByIdAsync(Guid i,CancellationToken c=default)=>Task.FromResult(D.SingleOrDefault(x=>x.Id==i));public Task<Claim?> GetReviewByIdAsync(Guid i,CancellationToken c=default)=>Task.FromResult(D.SingleOrDefault(x=>x.Id==i));public Task<IReadOnlyList<Claim>> GetAllAsync(CancellationToken c=default)=>Task.FromResult((IReadOnlyList<Claim>)D);public Task<IReadOnlyList<Claim>> GetByStatusAsync(string s,CancellationToken c=default)=>Task.FromResult((IReadOnlyList<Claim>)D);public Task<IReadOnlyList<Claim>> GetByClaimantIdAsync(string i,CancellationToken c=default)=>Task.FromResult((IReadOnlyList<Claim>)D.Where(x=>x.ClaimantUserId==i).ToList());public Task<IReadOnlyList<Claim>> GetByFoundItemIdAsync(Guid i,CancellationToken c=default)=>Task.FromResult((IReadOnlyList<Claim>)D);public void Update(Claim x){}public Task SaveChangesAsync(CancellationToken c=default)=>Task.CompletedTask;}
 sealed class V:IClaimVerificationRepository{public List<ClaimVerification>D=[];public Task<ClaimVerification?> GetByClaimIdAsync(Guid i,CancellationToken c=default)=>Task.FromResult(D.SingleOrDefault(x=>x.ClaimId==i));public Task<ClaimVerification?> GetByMatchIdAsync(Guid i,CancellationToken c=default)=>Task.FromResult(D.SingleOrDefault(x=>x.MatchId==i));public Task<IReadOnlyList<ClaimVerification>> GetPendingSecurityReviewAsync(CancellationToken c=default)=>Task.FromResult((IReadOnlyList<ClaimVerification>)D.Where(x=>x.Status=="PendingSecurityReview").ToList());public Task AddAsync(ClaimVerification x,CancellationToken c=default){D.Add(x);return Task.CompletedTask;}public Task UpdateAsync(ClaimVerification x,CancellationToken c=default)=>Task.CompletedTask;public Task EnsureTableCreatedAsync(CancellationToken c=default)=>Task.CompletedTask;}
 sealed class U:IUserRepository{public Task<IReadOnlyList<ApplicationUser>> GetByRoleAsync(UserRole r,CancellationToken c=default)=>Task.FromResult((IReadOnlyList<ApplicationUser>)[]);public Task<ApplicationUser?> GetByEmailAsync(string s,CancellationToken c=default)=>Task.FromResult<ApplicationUser?>(null);public Task<ApplicationUser?> GetByIdAsync(string s,CancellationToken c=default)=>Task.FromResult<ApplicationUser?>(null);public Task<IReadOnlyList<string>> GetRolesAsync(string s,CancellationToken c=default)=>Task.FromResult((IReadOnlyList<string>)[]);public Task CreateAsync(ApplicationUser x,CancellationToken c=default)=>Task.CompletedTask;public Task AddToRoleAsync(string a,string b,CancellationToken c=default)=>Task.CompletedTask;public Task EnsureRoleExistsAsync(string a,CancellationToken c=default)=>Task.CompletedTask;public Task UpdatePasswordHashAsync(string a,string b,CancellationToken c=default)=>Task.CompletedTask;}
 sealed class A:IAuditLogService{public List<string>D=[];public Task LogAsync(string? u,string a,string? d=null,CancellationToken c=default){D.Add(d??"");return Task.CompletedTask;}public Task<IReadOnlyList<LoginHistoryEntryDto>> GetLoginHistoryAsync(string s,int t=20,CancellationToken c=default)=>Task.FromResult((IReadOnlyList<LoginHistoryEntryDto>)[]);public Task<LoginHistoryEntryDto?> GetLoginDetailAsync(string s,Guid i,CancellationToken c=default)=>Task.FromResult<LoginHistoryEntryDto?>(null);} sealed class N:INotificationService{public List<string>Messages=[];public Task CreateAsync(string u,string m,CancellationToken c=default){Messages.Add(u+":"+m);return Task.CompletedTask;}}
}
