import { useEffect, useState } from 'react';
import { approveAccessRequest, getAccessRequests, rejectAccessRequest, type AccessRequest } from '../../services/accessRequestService';
import { getApiError } from '../../services/apiError';
import { Notice } from '../../components/Notice';

export function SecurityOfficerRequestsPage() {
  const [requests, setRequests] = useState<AccessRequest[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [busy, setBusy] = useState('');
  async function load() { try { setLoading(true); setRequests(await getAccessRequests()); } catch (e) { setError(getApiError(e, 'Could not load Security Officer requests.')); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function decide(request: AccessRequest, approve: boolean) { const rejectionReason = approve ? '' : window.prompt('Why is this request being rejected?') ?? ''; if (!approve && !rejectionReason.trim()) return; try { setBusy(request.id); setError(''); await (approve ? approveAccessRequest(request.id) : rejectAccessRequest(request.id, rejectionReason)); await load(); } catch (e) { setError(getApiError(e, 'Could not update this request.')); } finally { setBusy(''); } }
  return <main className="wide-main"><div className="section-heading"><div><p className="eyebrow">Administrator workspace</p><h1>Security Officer requests</h1><p className="muted">Review requests before granting operational access.</p></div><button className="button button-secondary" type="button" onClick={() => void load()} disabled={loading}>Refresh</button></div>{error && <Notice>{error}</Notice>}{loading ? <p className="loading">Loading access requests...</p> : requests.length === 0 ? <p className="empty-state">No Security Officer requests have been submitted.</p> : <div className="admin-request-list">{requests.map(request => <article className="admin-request-card" key={request.id}><div><span className={`badge badge-${request.status.toLowerCase()}`}>{request.status}</span><h3>{request.fullName || 'Name not provided'}</h3><p>{request.email}{request.department ? ` · ${request.department}` : ''}{request.staffId ? ` · ${request.staffId}` : ''}</p><p className="muted">{request.reason}</p><small>Submitted {new Date(request.createdAt).toLocaleString()}</small></div>{request.status === 'Pending' && <div className="button-row"><button className="button-approve" type="button" disabled={busy === request.id} onClick={() => void decide(request, true)}>Approve</button><button className="button-reject" type="button" disabled={busy === request.id} onClick={() => void decide(request, false)}>Reject</button></div>}</article>)}</div>}</main>;
}