import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Alert, PageLoading } from '../../components/Ui';
import { startOwnershipVerification, submitOwnershipVerification } from '../../api/ownershipVerification';

export default function OwnershipVerificationPage() {
  const { matchId } = useParams(); const navigate = useNavigate();
  const [verification, setVerification] = useState(null); const [answers, setAnswers] = useState([]); const [step, setStep] = useState(0); const [error, setError] = useState(''); const [result, setResult] = useState(null); const [saving, setSaving] = useState(false);
  useEffect(() => { startOwnershipVerification(matchId).then(v => { setVerification(v); setAnswers(v.questions.map(() => '')); }).catch(e => setError(e.message)); }, [matchId]);
  if (error && !verification) return <div className="page-container-form"><Alert type="error">{error}</Alert><Link className="btn btn-secondary" to="/my-matches">Back to My AI Matches</Link></div>;
  if (!verification) return <PageLoading label="Preparing ownership verification…" />;
  if (result) return <div className="page-container-form"><div className="card card-pad-lg" style={{ textAlign: 'center' }}><span className="eyebrow">Ownership Verification</span><h1>Verification submitted</h1><p className="text-secondary">{result.message}</p><p style={{ fontWeight: 700 }}>Status: Pending Security Review</p><Link className="btn btn-primary" to="/my-matches">Return to My AI Matches</Link></div></div>;
  const question = verification.questions[step];
  const submit = async () => { setError(''); setSaving(true); try { setResult(await submitOwnershipVerification(matchId, answers.map(a => a.trim()))); } catch (e) { setError(e.message); } finally { setSaving(false); } };
  return <div className="page-container-form"><div className="card card-pad-lg"><span className="eyebrow">Secure ownership gate</span><h1>Ownership Verification</h1><p className="text-secondary">Answer details that only the real owner would reasonably know. Your answers are sent to Security for manual review.</p><div style={{ margin: '28px 0 10px', fontWeight: 700 }}>Question {step + 1} of {verification.questions.length}</div><div className="progress-track"><div className="progress-fill" style={{ width: `${((step + 1) / verification.questions.length) * 100}%` }} /></div><h2 style={{ marginTop: 28 }}>{question.question}</h2><textarea aria-label={`Answer to question ${step + 1}`} value={answers[step]} onChange={e => setAnswers(values => values.map((value, index) => index === step ? e.target.value : value))} maxLength={1000} rows={6} placeholder="Enter your answer" /><p className="hint">{answers[step].length}/1000 characters</p><Alert type="error">{error}</Alert><div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, marginTop: 24 }}><button className="btn btn-secondary" onClick={() => step ? setStep(step - 1) : navigate('/my-matches')}>{step ? 'Back' : 'Cancel'}</button>{step < verification.questions.length - 1 ? <button className="btn btn-primary" disabled={!answers[step].trim()} onClick={() => setStep(step + 1)}>Next</button> : <button className="btn btn-primary" disabled={saving || answers.some(a => !a.trim())} onClick={submit}>{saving ? 'Submitting…' : 'Submit for Security Review'}</button>}</div></div></div>;
}
