import { useEffect, useState } from 'react';
import { getAnalytics } from '../api/adminAnalytics';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, LineChart, Line, PieChart, Pie, Cell } from 'recharts';

const COLORS = ['#166534', '#0F766E', '#7C6CC4', '#dc2626', '#d97706'];
export default function AdminAnalyticsPage(){
 const [overview,setOverview]=useState(null);const [items,setItems]=useState(null);const [claims,setClaims]=useState(null);const [locations,setLocations]=useState([]);const [users,setUsers]=useState(null);const [range,setRange]=useState('30');const [error,setError]=useState('');
 useEffect(()=>{const to=new Date();const from=new Date();from.setDate(from.getDate()-Number(range));const filters={from:from.toISOString(),to:to.toISOString()};Promise.all([getAnalytics('overview',filters),getAnalytics('items',filters),getAnalytics('claims',filters),getAnalytics('locations'),getAnalytics('users')]).then(([a,b,c,d,e])=>{setOverview(a);setItems(b);setClaims(c);setLocations(d);setUsers(e)}).catch(e=>setError(e.message))},[range]);
 const exportCsv=()=>{if(!items)return;const rows=[['Year','Month','Lost','Found'],...items.monthly.map(x=>[x.year,x.month,x.lost,x.found])];const csv=rows.map(row=>row.join(',')).join('\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));link.download='campusfind-analytics.csv';link.click();URL.revokeObjectURL(link.href)};
 return <section className="page-container"><header className="page-header"><h1>Platform analytics</h1><p>CampusFind activity from the application database</p></header><div style={{display:'flex',gap:12,marginBottom:20}}><label>Date range <select value={range} onChange={e=>setRange(e.target.value)}><option value="1">Today</option><option value="7">7 days</option><option value="30">30 days</option><option value="90">90 days</option><option value="365">1 year</option></select></label><button className="btn btn-secondary" onClick={exportCsv}>Export CSV</button></div>{error&&<p role="alert">{error}</p>}{!overview?<p>Loading analytics…</p>:<><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(140px,1fr))',gap:12}}>{Object.entries(overview).map(([key,value])=><div className="card" key={key} style={{padding:20}}><div className="text-muted">{key}</div><strong style={{fontSize:28}}>{value}</strong></div>)}</div><p>Active users: {users?.active??0} · Claim recovery rate: {claims?.recoveryRate??0}% · Average resolution: {claims?.averageResolutionHours??0} hours</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:22,marginTop:24}}>
 <div className="card" style={{padding:18}}><h2>Lost vs found reports</h2><div style={{height:260}}><ResponsiveContainer><LineChart data={items?.monthly||[]}><XAxis dataKey="month"/><YAxis/><Tooltip/><Line dataKey="lost" stroke="#dc2626"/><Line dataKey="found" stroke="#166534"/></LineChart></ResponsiveContainer></div></div>
 <div className="card" style={{padding:18}}><h2>Category distribution</h2><div style={{height:260}}><ResponsiveContainer><BarChart data={items?.categories||[]}><XAxis dataKey="name" hide/><YAxis/><Tooltip/><Bar dataKey="count" fill="#0F766E"/></BarChart></ResponsiveContainer></div></div>
 <div className="card" style={{padding:18}}><h2>Claim status</h2><div style={{height:260}}><ResponsiveContainer><PieChart><Pie data={claims?.status||[]} dataKey="count" nameKey="status" outerRadius={90} label>{(claims?.status||[]).map((x,i)=><Cell key={x.status} fill={COLORS[i%COLORS.length]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div></div>
 <div className="card" style={{padding:18}}><h2>Top locations</h2><div style={{height:260}}><ResponsiveContainer><BarChart data={locations} layout="vertical"><XAxis type="number"/><YAxis type="category" dataKey="name" width={110}/><Tooltip/><Bar dataKey="count" fill="#7C6CC4"/></BarChart></ResponsiveContainer></div></div>
 </div></>}</section>
}
