import { useEffect, useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { Alert, ButtonSpinner, PageLoading } from '../components/Ui';
import { getSupportPayment, getSupportPaymentAvailability, submitManualSupportReference } from '../api/supportPayments';

export default function ManualSupportPaymentPage() {
  const [params] = useSearchParams(); const navigate = useNavigate(); const id = params.get('id');
  const [payment, setPayment] = useState(null); const [config, setConfig] = useState(null); const [reference, setReference] = useState(''); const [copied, setCopied] = useState(false); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!id) { navigate('/support', { replace: true }); return; } Promise.all([getSupportPayment(id), getSupportPaymentAvailability()]).then(([item, availability]) => { setPayment(item); setConfig(availability); }).catch(err => setError(err.message)); }, [id, navigate]);
  async function copyNumber() { try { await navigator.clipboard.writeText(config.recipientNumber); setCopied(true); } catch { setError('Copy the receiving number manually.'); } }
  async function submit(event) { event.preventDefault(); if (!reference.trim() || saving) return; setSaving(true); setError(''); try { await submitManualSupportReference(id, reference.trim()); navigate(`/support/awaiting-confirmation?id=${id}`, { replace: true }); } catch (err) { setError(err.message || 'We could not record that reference.'); } finally { setSaving(false); } }
  if ((!payment || !config) && !error) return <PageLoading label="Preparing payment instructions…" />;
  if (error && (!payment || !config)) return <section className="page-container-form"><Alert type="error">{error}</Alert><Link className="btn btn-secondary" to="/support">Back to support</Link></section>;
  return <section className="page-container-form"><div className="card card-pad-lg"><span className="eyebrow">Support CampusFind</span><h1>Send via {payment.provider}</h1><p className="text-secondary">Open your own {payment.provider} app and send the exact amount below. Enter your PIN or OTP only inside the official wallet app.</p><div style={{ padding: 20, margin: '22px 0', background: 'var(--surface-muted)', borderRadius: 12 }}><div className="text-secondary text-sm">Amount to send</div><strong style={{ fontSize: '1.6rem' }}>৳{payment.amount}</strong><div className="text-secondary text-sm" style={{ marginTop: 16 }}>Send to</div><strong>{config.recipientName}</strong><div style={{ display: 'flex', alignItems: 'center', gap: 12, marginTop: 6, flexWrap: 'wrap' }}><code style={{ fontSize: '1.15rem' }}>{config.recipientNumber}</code><button type="button" className="btn btn-secondary" onClick={copyNumber}>{copied ? 'Copied' : 'Copy number'}</button></div><p className="text-secondary text-sm" style={{ marginBottom: 0, marginTop: 14 }}>Reference: {payment.merchantInvoiceNumber}</p></div><form onSubmit={submit}><label>Transaction ID / reference<input value={reference} onChange={event => setReference(event.target.value)} minLength="4" maxLength="128" required placeholder="Enter the reference from your wallet receipt" /></label><p className="hint">We record this reference for review. Submitting it does not automatically confirm payment.</p>{error && <Alert type="error">{error}</Alert>}<div style={{ display: 'flex', gap: 12, flexWrap: 'wrap' }}><button className="btn btn-primary" disabled={saving}>{saving ? <ButtonSpinner /> : 'Submit for confirmation'}</button><Link className="btn btn-ghost" to="/support">Cancel</Link></div></form></div></section>;
}
