import { useEffect, useState, type FormEvent } from 'react';
import { createAccessRequest, getMyAccessRequests, type AccessRequest } from '../../services/accessRequestService';
import { getApiError } from '../../services/apiError';
import { Notice } from '../../components/Notice';
import { useAuth } from '../../context/AuthContext';

export function AccessRequestPage() {
  const { user } = useAuth();
  const [requests, setRequests] = useState<AccessRequest[]>([]); const [fullName, setFullName] = useState(''); const [staffId, setStaffId] = useState(''); const [department, setDepartment] = useState(''); const [reason, setReason] = useState(''); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('');
  async function load() { try { setLoading(true); setRequests(await getMyAccessRequests()); } catch (e) { setError(getApiError(e, 'Could not load your access requests.')); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); setSuccess(''); setSubmitting(true); try { await createAccessRequest({ fullName: fullName.trim() || undefined, staffId: staffId.trim() || undefined, department: department.trim() || undefined, reason: reason.trim() }); setFullName(''); setStaffId(''); setDepartment(''); setReason(''); setSuccess('Your Security Officer access request has been submitted.'); await load(); } catch (e) { setError(getApiError(e, 'Could not submit your access request.')); } finally { setSubmitting(false); } }
  const pending = requests.some(request => request.status === 'Pending');
  return <main className="wide-main access-request-page"><div className="page-intro"><p className="eyebrow">Role elevation</p><h1>Security Officer access</h1><p className="muted">Security Officer access requires administrator approval. Submit your campus credentials and a clear reason for review.</p></div><div className="content-grid access-grid"><section className="form-panel"><form onSubmit={submit}><label>Full name<input value={fullName} onChange={event => setFullName(event.target.value)} maxLength={256} required placeholder="Your full name" /></label><label>University email<input value={user?.email ?? ''} readOnly placeholder="Verified from your account" /></label><label>Staff / employee ID <span className="muted">(optional)</span><input value={staffId} onChange={event => setStaffId(event.target.value)} maxLength={100} /></label><label>Department <span className="muted">(optional)</span><input value={department} onChange={event => setDepartment(event.target.value)} maxLength={200} placeholder="e.g. Campus Safety" /></label><label>Reason for requesting access<textarea value={reason} onChange={event => setReason(event.target.value)} required minLength={10} maxLength={4000} rows={6} placeholder="Explain your responsibilities and why this role is needed." /></label><button className="button" type="submit" disabled={submitting || pending}>{submitting ? 'Submitting...' : pending ? 'Request under review' : 'Submit access request'}</button></form>{error && <Notice>{error}</Notice>}{success && <Notice type="success">{success}</Notice>}</section><section className="reports-panel"><div className="section-heading"><div><p className="eyebrow">Review status</p><h2>Your requests</h2></div><button className="button button-secondary" type="button" onClick={() => void load()} disabled={loading}>Refresh</button></div>{loading ? <p className="loading">Loading request history...</p> : requests.length === 0 ? <p className="empty-state">No access requests yet.</p> : <div className="report-list">{requests.map(request => <article className="report-card" key={request.id}><div><h4>{request.status === 'Pending' ? 'Pending administrator review' : `Request ${request.status.toLowerCase()}`}</h4><p>{request.reason}</p><small>Submitted {new Date(request.createdAt).toLocaleString()}</small>{request.rejectionReason && <p className="request-rejection">Reason: {request.rejectionReason}</p>}</div><span className={`badge badge-${request.status.toLowerCase()}`}>{request.status}</span></article>)}</div>}</section></div></main>;
}